id: I511C49C9
legacy_id: P003079
ocr_import_info:
  bdrc_scan_id: W00KG03992
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T01:03:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:18:56.141947+00:00'
last_modified: 2022-08-29 20:19:06.890037
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03992
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03992
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཛམ་གླིང་རྒྱས་བཤད་ཀྱི་ལྷན་ཐབས།
  author: ཤེས་རབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6174446386795291
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I00KG04031:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG04031
      total_pages: 43
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG04031.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6174446386795291
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
