id: I511C49C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:03:30+00:00'
last_modified: '2022-06-07T17:25:17.279665+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03992
  title: འཛམ་གླིང་རྒྱས་བཤད་ཀྱི་ལྷན་ཐབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D550:
      image_group_id: I00KG04031
      title: ''
      total_pages: 43
      order: 1
      base_file: D550.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
